// Auto-generated by gen_wrappers.py — do not edit
// Missing AnimImage wrappers for LVGL C functions

[[nodiscard]] lv_anim_t* get_anim() const noexcept {
    return lv_animimg_get_anim(m_obj);
}

[[nodiscard]] uint32_t get_duration() const noexcept {
    return lv_animimg_get_duration(m_obj);
}

[[nodiscard]] uint32_t get_repeat_count() const noexcept {
    return lv_animimg_get_repeat_count(m_obj);
}

[[nodiscard]] const void* * get_src() const noexcept {
    return lv_animimg_get_src(m_obj);
}

[[nodiscard]] uint8_t get_src_count() const noexcept {
    return lv_animimg_get_src_count(m_obj);
}

AnimImage& set_completed_cb(lv_anim_completed_cb_t completed_cb) noexcept {
    lv_animimg_set_completed_cb(m_obj, completed_cb);
    return *this;
}

AnimImage& set_reverse_delay(uint32_t duration) noexcept {
    lv_animimg_set_reverse_delay(m_obj, duration);
    return *this;
}

AnimImage& set_reverse_duration(uint32_t duration) noexcept {
    lv_animimg_set_reverse_duration(m_obj, duration);
    return *this;
}

AnimImage& set_start_cb(lv_anim_start_cb_t start_cb) noexcept {
    lv_animimg_set_start_cb(m_obj, start_cb);
    return *this;
}

