// Auto-generated by gen_wrappers.py — do not edit
// Missing Arc wrappers for LVGL C functions

void align_obj_to_angle(lv_obj_t * obj_to_align, int32_t r_offset) const noexcept {
    lv_arc_align_obj_to_angle(m_obj, obj_to_align, r_offset);
}

[[nodiscard]] lv_value_precise_t get_angle_end() const noexcept {
    return lv_arc_get_angle_end(m_obj);
}

[[nodiscard]] lv_value_precise_t get_angle_start() const noexcept {
    return lv_arc_get_angle_start(m_obj);
}

[[nodiscard]] lv_value_precise_t get_bg_angle_end() const noexcept {
    return lv_arc_get_bg_angle_end(m_obj);
}

[[nodiscard]] lv_value_precise_t get_bg_angle_start() const noexcept {
    return lv_arc_get_bg_angle_start(m_obj);
}

[[nodiscard]] uint32_t get_change_rate() const noexcept {
    return lv_arc_get_change_rate(m_obj);
}

[[nodiscard]] int32_t get_knob_offset() const noexcept {
    return lv_arc_get_knob_offset(m_obj);
}

Arc& set_change_rate(uint32_t rate) noexcept {
    lv_arc_set_change_rate(m_obj, rate);
    return *this;
}

Arc& set_max_value(int32_t max) noexcept {
    lv_arc_set_max_value(m_obj, max);
    return *this;
}

Arc& set_min_value(int32_t min) noexcept {
    lv_arc_set_min_value(m_obj, min);
    return *this;
}

