// Auto-generated by gen_wrappers.py — do not edit
// Missing ArcLabel wrappers for LVGL C functions

[[nodiscard]] bool get_end_overlap() const noexcept {
    return lv_arclabel_get_end_overlap(m_obj);
}

ArcLabel& set_end_overlap(bool overlap) noexcept {
    lv_arclabel_set_end_overlap(m_obj, overlap);
    return *this;
}

