// Auto-generated by gen_wrappers.py — do not edit
// Missing Bar wrappers for LVGL C functions

[[nodiscard]] lv_bar_orientation_t get_orientation() const noexcept {
    return lv_bar_get_orientation(m_obj);
}

[[nodiscard]] bool is_symmetrical() const noexcept {
    return lv_bar_is_symmetrical(m_obj);
}

Bar& set_max_value(int32_t max) noexcept {
    lv_bar_set_max_value(m_obj, max);
    return *this;
}

Bar& set_min_value(int32_t min) noexcept {
    lv_bar_set_min_value(m_obj, min);
    return *this;
}

