// Auto-generated by gen_wrappers.py — do not edit
// Missing ButtonMatrix wrappers for LVGL C functions

[[nodiscard]] const char* const* get_map() const noexcept {
    return lv_buttonmatrix_get_map(m_obj);
}

ButtonMatrix& set_button_width(uint32_t btn_id, uint32_t width) noexcept {
    lv_buttonmatrix_set_button_width(m_obj, btn_id, width);
    return *this;
}

