// Auto-generated by gen_wrappers.py — do not edit
// Missing Calendar wrappers for LVGL C functions

lv_obj_t* add_header_arrow() noexcept {
    return lv_calendar_add_header_arrow(m_obj);
}

lv_obj_t* add_header_dropdown() noexcept {
    return lv_calendar_add_header_dropdown(m_obj);
}

[[nodiscard]] lv_obj_t* get_btnmatrix() const noexcept {
    return lv_calendar_get_btnmatrix(m_obj);
}

Calendar& header_dropdown_set_year_list(const char * years_list) noexcept {
    lv_calendar_header_dropdown_set_year_list(m_obj, years_list);
    return *this;
}

Calendar& set_month_shown(uint32_t year, uint32_t month) noexcept {
    lv_calendar_set_month_shown(m_obj, year, month);
    return *this;
}

Calendar& set_shown_month(uint32_t month) noexcept {
    lv_calendar_set_shown_month(m_obj, month);
    return *this;
}

Calendar& set_shown_year(uint32_t year) noexcept {
    lv_calendar_set_shown_year(m_obj, year);
    return *this;
}

Calendar& set_today_day(uint32_t day) noexcept {
    lv_calendar_set_today_day(m_obj, day);
    return *this;
}

Calendar& set_today_month(uint32_t month) noexcept {
    lv_calendar_set_today_month(m_obj, month);
    return *this;
}

Calendar& set_today_year(uint32_t year) noexcept {
    lv_calendar_set_today_year(m_obj, year);
    return *this;
}

