// Auto-generated by gen_wrappers.py — do not edit
// Missing Chart wrappers for LVGL C functions

[[nodiscard]] lv_point_t get_cursor_point(lv_chart_cursor_t * cursor) const noexcept {
    return lv_chart_get_cursor_point(m_obj, cursor);
}

