// Auto-generated by gen_wrappers.py — do not edit
// Missing Dropdown wrappers for LVGL C functions

[[nodiscard]] lv_dir_t get_dir() const noexcept {
    return lv_dropdown_get_dir(m_obj);
}

[[nodiscard]] int32_t get_option_index(const char * option) const noexcept {
    return lv_dropdown_get_option_index(m_obj, option);
}

[[nodiscard]] const char* get_options() const noexcept {
    return lv_dropdown_get_options(m_obj);
}

[[nodiscard]] bool get_selected_highlight() const noexcept {
    return lv_dropdown_get_selected_highlight(m_obj);
}

[[nodiscard]] const char* get_symbol() const noexcept {
    return lv_dropdown_get_symbol(m_obj);
}

[[nodiscard]] const char* get_text() const noexcept {
    return lv_dropdown_get_text(m_obj);
}

Dropdown& set_text_static(const char * text) noexcept {
    lv_dropdown_set_text_static(m_obj, text);
    return *this;
}

