// Auto-generated by gen_wrappers.py — do not edit
// Missing ImageButton wrappers for LVGL C functions

ImageButton& set_src_left(lv_imagebutton_state_t state, const void * src_left) noexcept {
    lv_imagebutton_set_src_left(m_obj, state, src_left);
    return *this;
}

ImageButton& set_src_mid(lv_imagebutton_state_t state, const void * src_mid) noexcept {
    lv_imagebutton_set_src_mid(m_obj, state, src_mid);
    return *this;
}

ImageButton& set_src_right(lv_imagebutton_state_t state, const void * src_right) noexcept {
    lv_imagebutton_set_src_right(m_obj, state, src_right);
    return *this;
}

ImageButton& set_state(lv_imagebutton_state_t state) noexcept {
    lv_imagebutton_set_state(m_obj, state);
    return *this;
}

