// Auto-generated by gen_wrappers.py — do not edit
// Missing Image wrappers for LVGL C functions

lv_observer_t* bind_src(lv_subject_t * subject) noexcept {
    return lv_image_bind_src(m_obj, subject);
}

[[nodiscard]] const lv_image_dsc_t* get_bitmap_map_src() const noexcept {
    return lv_image_get_bitmap_map_src(m_obj);
}

[[nodiscard]] lv_image_align_t get_inner_align() const noexcept {
    return lv_image_get_inner_align(m_obj);
}

void get_pivot(lv_point_t * pivot) const noexcept {
    lv_image_get_pivot(m_obj, pivot);
}

[[nodiscard]] int32_t get_scale_x() const noexcept {
    return lv_image_get_scale_x(m_obj);
}

[[nodiscard]] int32_t get_scale_y() const noexcept {
    return lv_image_get_scale_y(m_obj);
}

[[nodiscard]] int32_t get_src_height() const noexcept {
    return lv_image_get_src_height(m_obj);
}

[[nodiscard]] int32_t get_src_width() const noexcept {
    return lv_image_get_src_width(m_obj);
}

[[nodiscard]] int32_t get_transformed_height() const noexcept {
    return lv_image_get_transformed_height(m_obj);
}

[[nodiscard]] int32_t get_transformed_width() const noexcept {
    return lv_image_get_transformed_width(m_obj);
}

Image& set_bitmap_map_src(const lv_image_dsc_t * src) noexcept {
    lv_image_set_bitmap_map_src(m_obj, src);
    return *this;
}

Image& set_pivot_x(int32_t x) noexcept {
    lv_image_set_pivot_x(m_obj, x);
    return *this;
}

Image& set_pivot_y(int32_t y) noexcept {
    lv_image_set_pivot_y(m_obj, y);
    return *this;
}

