// Auto-generated by gen_wrappers.py — do not edit
// Missing Keyboard wrappers for LVGL C functions

[[nodiscard]] const char* get_button_text(uint32_t btn_id) const noexcept {
    return lv_keyboard_get_button_text(m_obj, btn_id);
}

[[nodiscard]] const char* const* get_map_array() const noexcept {
    return lv_keyboard_get_map_array(m_obj);
}

[[nodiscard]] bool get_popovers() const noexcept {
    return lv_keyboard_get_popovers(m_obj);
}

[[nodiscard]] uint32_t get_selected_button() const noexcept {
    return lv_keyboard_get_selected_button(m_obj);
}

