// Auto-generated by gen_wrappers.py — do not edit
// Missing Label wrappers for LVGL C functions

Label& cut_text(uint32_t pos, uint32_t cnt) noexcept {
    lv_label_cut_text(m_obj, pos, cnt);
    return *this;
}

[[nodiscard]] uint32_t get_letter_on(lv_point_t * pos_in, bool bidi) const noexcept {
    return lv_label_get_letter_on(m_obj, pos_in, bidi);
}

void get_letter_pos(uint32_t char_id, lv_point_t * pos) const noexcept {
    lv_label_get_letter_pos(m_obj, char_id, pos);
}

[[nodiscard]] lv_label_long_mode_t get_long_mode() const noexcept {
    return lv_label_get_long_mode(m_obj);
}

[[nodiscard]] bool get_recolor() const noexcept {
    return lv_label_get_recolor(m_obj);
}

[[nodiscard]] uint32_t get_text_selection_end() const noexcept {
    return lv_label_get_text_selection_end(m_obj);
}

[[nodiscard]] uint32_t get_text_selection_start() const noexcept {
    return lv_label_get_text_selection_start(m_obj);
}

Label& ins_text(uint32_t pos, const char * txt) noexcept {
    lv_label_ins_text(m_obj, pos, txt);
    return *this;
}

[[nodiscard]] bool is_char_under_pos(lv_point_t * pos) const noexcept {
    return lv_label_is_char_under_pos(m_obj, pos);
}

