// Auto-generated by gen_wrappers.py — do not edit
// Missing Line wrappers for LVGL C functions

[[nodiscard]] uint32_t get_point_count() const noexcept {
    return lv_line_get_point_count(m_obj);
}

[[nodiscard]] const lv_point_precise_t* get_points() const noexcept {
    return lv_line_get_points(m_obj);
}

[[nodiscard]] lv_point_precise_t* get_points_mutable() const noexcept {
    return lv_line_get_points_mutable(m_obj);
}

[[nodiscard]] bool is_point_array_mutable() const noexcept {
    return lv_line_is_point_array_mutable(m_obj);
}

