// Auto-generated by gen_wrappers.py — do not edit
// Missing List wrappers for LVGL C functions

lv_obj_t* add_button_translation_tag(const void * icon, const char * tag) noexcept {
    return lv_list_add_button_translation_tag(m_obj, icon, tag);
}

lv_obj_t* add_translation_tag(const char * tag) noexcept {
    return lv_list_add_translation_tag(m_obj, tag);
}

List& set_button_text(lv_obj_t * btn, const char * txt) noexcept {
    lv_list_set_button_text(m_obj, btn, txt);
    return *this;
}

List& set_button_translation_tag(lv_obj_t * btn, const char * tag) noexcept {
    lv_list_set_button_translation_tag(m_obj, btn, tag);
    return *this;
}

