// Auto-generated by gen_wrappers.py — do not edit
// Missing Menu wrappers for LVGL C functions

bool back_button_is_root(lv_obj_t * obj) noexcept {
    return lv_menu_back_button_is_root(m_obj, obj);
}

[[nodiscard]] lv_menu_mode_header_t get_mode_header() const noexcept {
    return lv_menu_get_mode_header(m_obj);
}

[[nodiscard]] lv_menu_mode_root_back_button_t get_mode_root_back_button() const noexcept {
    return lv_menu_get_mode_root_back_button(m_obj);
}

Menu& set_page_title(char const * const title) noexcept {
    lv_menu_set_page_title(m_obj, title);
    return *this;
}

Menu& set_page_title_static(char const * const title) noexcept {
    lv_menu_set_page_title_static(m_obj, title);
    return *this;
}

