// Auto-generated by gen_wrappers.py — do not edit
// Missing Roller wrappers for LVGL C functions

[[nodiscard]] lv_result_t get_option_str(uint32_t option, char * buf, uint32_t buf_size) const noexcept {
    return lv_roller_get_option_str(m_obj, option, buf, buf_size);
}

[[nodiscard]] const char* get_options() const noexcept {
    return lv_roller_get_options(m_obj);
}

bool set_selected_str(const char * sel_opt, lv_anim_enable_t anim) noexcept {
    return lv_roller_set_selected_str(m_obj, sel_opt, anim);
}

