// Auto-generated by gen_wrappers.py — do not edit
// Missing Scale wrappers for LVGL C functions

lv_observer_t* bind_image_needle_value(lv_obj_t * needle_img, lv_subject_t * subject) noexcept {
    return lv_scale_bind_image_needle_value(m_obj, needle_img, subject);
}

lv_observer_t* bind_line_needle_value(lv_obj_t * needle_line, int32_t needle_length, lv_subject_t * subject) noexcept {
    return lv_scale_bind_line_needle_value(m_obj, needle_line, needle_length, subject);
}

lv_observer_t* bind_section_max_value(lv_scale_section_t * section, lv_subject_t * subject) noexcept {
    return lv_scale_bind_section_max_value(m_obj, section, subject);
}

lv_observer_t* bind_section_min_value(lv_scale_section_t * section, lv_subject_t * subject) noexcept {
    return lv_scale_bind_section_min_value(m_obj, section, subject);
}

[[nodiscard]] uint32_t get_angle_range() const noexcept {
    return lv_scale_get_angle_range(m_obj);
}

[[nodiscard]] bool get_label_show() const noexcept {
    return lv_scale_get_label_show(m_obj);
}

[[nodiscard]] int32_t get_major_tick_every() const noexcept {
    return lv_scale_get_major_tick_every(m_obj);
}

[[nodiscard]] lv_scale_mode_t get_mode() const noexcept {
    return lv_scale_get_mode(m_obj);
}

[[nodiscard]] int32_t get_range_max_value() const noexcept {
    return lv_scale_get_range_max_value(m_obj);
}

[[nodiscard]] int32_t get_range_min_value() const noexcept {
    return lv_scale_get_range_min_value(m_obj);
}

[[nodiscard]] int32_t get_rotation() const noexcept {
    return lv_scale_get_rotation(m_obj);
}

[[nodiscard]] int32_t get_total_tick_count() const noexcept {
    return lv_scale_get_total_tick_count(m_obj);
}

Scale& set_draw_ticks_on_top(bool en) noexcept {
    lv_scale_set_draw_ticks_on_top(m_obj, en);
    return *this;
}

Scale& set_image_needle_value(lv_obj_t * needle_img, int32_t value) noexcept {
    lv_scale_set_image_needle_value(m_obj, needle_img, value);
    return *this;
}

Scale& set_line_needle_value(lv_obj_t * needle_line, int32_t needle_length, int32_t value) noexcept {
    lv_scale_set_line_needle_value(m_obj, needle_line, needle_length, value);
    return *this;
}

Scale& set_max_value(int32_t max) noexcept {
    lv_scale_set_max_value(m_obj, max);
    return *this;
}

Scale& set_min_value(int32_t min) noexcept {
    lv_scale_set_min_value(m_obj, min);
    return *this;
}

Scale& set_section_max_value(lv_scale_section_t * section, int32_t max) noexcept {
    lv_scale_set_section_max_value(m_obj, section, max);
    return *this;
}

Scale& set_section_min_value(lv_scale_section_t * section, int32_t min) noexcept {
    lv_scale_set_section_min_value(m_obj, section, min);
    return *this;
}

Scale& set_section_range(lv_scale_section_t * section, int32_t min, int32_t max) noexcept {
    lv_scale_set_section_range(m_obj, section, min, max);
    return *this;
}

Scale& set_section_style_indicator(lv_scale_section_t * section, const lv_style_t * style) noexcept {
    lv_scale_set_section_style_indicator(m_obj, section, style);
    return *this;
}

Scale& set_section_style_items(lv_scale_section_t * section, const lv_style_t * style) noexcept {
    lv_scale_set_section_style_items(m_obj, section, style);
    return *this;
}

Scale& set_section_style_main(lv_scale_section_t * section, const lv_style_t * style) noexcept {
    lv_scale_set_section_style_main(m_obj, section, style);
    return *this;
}

