// Auto-generated by gen_wrappers.py — do not edit
// Missing Slider wrappers for LVGL C functions

[[nodiscard]] lv_slider_mode_t get_mode() const noexcept {
    return lv_slider_get_mode(m_obj);
}

[[nodiscard]] lv_slider_orientation_t get_orientation() const noexcept {
    return lv_slider_get_orientation(m_obj);
}

[[nodiscard]] bool is_symmetrical() const noexcept {
    return lv_slider_is_symmetrical(m_obj);
}

Slider& set_max_value(int32_t max) noexcept {
    lv_slider_set_max_value(m_obj, max);
    return *this;
}

Slider& set_min_value(int32_t min) noexcept {
    lv_slider_set_min_value(m_obj, min);
    return *this;
}

Slider& set_orientation(lv_slider_orientation_t orientation) noexcept {
    lv_slider_set_orientation(m_obj, orientation);
    return *this;
}

