// Auto-generated by gen_wrappers.py — do not edit
// Missing Spangroup wrappers for LVGL C functions

lv_span_t* add_span() noexcept {
    return lv_spangroup_add_span(m_obj);
}

lv_observer_t* bind_span_text(lv_span_t * span, lv_subject_t * subject, const char * fmt) noexcept {
    return lv_spangroup_bind_span_text(m_obj, span, subject, fmt);
}

Spangroup& delete_span(lv_span_t * span) noexcept {
    lv_spangroup_delete_span(m_obj, span);
    return *this;
}

[[nodiscard]] lv_text_align_t get_align() const noexcept {
    return lv_spangroup_get_align(m_obj);
}

[[nodiscard]] int32_t get_expand_height(int32_t width) const noexcept {
    return lv_spangroup_get_expand_height(m_obj, width);
}

[[nodiscard]] uint32_t get_expand_width(uint32_t max_width) const noexcept {
    return lv_spangroup_get_expand_width(m_obj, max_width);
}

[[nodiscard]] int32_t get_indent() const noexcept {
    return lv_spangroup_get_indent(m_obj);
}

[[nodiscard]] int32_t get_max_line_height() const noexcept {
    return lv_spangroup_get_max_line_height(m_obj);
}

[[nodiscard]] int32_t get_max_lines() const noexcept {
    return lv_spangroup_get_max_lines(m_obj);
}

[[nodiscard]] lv_span_mode_t get_mode() const noexcept {
    return lv_spangroup_get_mode(m_obj);
}

[[nodiscard]] lv_span_overflow_t get_overflow() const noexcept {
    return lv_spangroup_get_overflow(m_obj);
}

[[nodiscard]] lv_span_t* get_span_by_point(const lv_point_t * point) const noexcept {
    return lv_spangroup_get_span_by_point(m_obj, point);
}

[[nodiscard]] lv_span_coords_t get_span_coords(const lv_span_t * span) const noexcept {
    return lv_spangroup_get_span_coords(m_obj, span);
}

Spangroup& refresh() noexcept {
    lv_spangroup_refresh(m_obj);
    return *this;
}

Spangroup& set_span_style(lv_span_t * span, const lv_style_t * style) noexcept {
    lv_spangroup_set_span_style(m_obj, span, style);
    return *this;
}

Spangroup& set_span_text(lv_span_t * span, const char * text) noexcept {
    lv_spangroup_set_span_text(m_obj, span, text);
    return *this;
}

Spangroup& set_span_text_static(lv_span_t * span, const char * text) noexcept {
    lv_spangroup_set_span_text_static(m_obj, span, text);
    return *this;
}

