// Auto-generated by gen_wrappers.py — do not edit
// Missing Spinner wrappers for LVGL C functions

[[nodiscard]] uint32_t get_anim_duration() const noexcept {
    return lv_spinner_get_anim_duration(m_obj);
}

[[nodiscard]] uint32_t get_arc_sweep() const noexcept {
    return lv_spinner_get_arc_sweep(m_obj);
}

Spinner& set_anim_duration(uint32_t t) noexcept {
    lv_spinner_set_anim_duration(m_obj, t);
    return *this;
}

Spinner& set_arc_sweep(uint32_t angle) noexcept {
    lv_spinner_set_arc_sweep(m_obj, angle);
    return *this;
}

