// Auto-generated by gen_wrappers.py — do not edit
// Missing Spinbox wrappers for LVGL C functions

lv_observer_t* bind_value(lv_subject_t * subject) noexcept {
    return lv_spinbox_bind_value(m_obj, subject);
}

[[nodiscard]] uint32_t get_dec_point_pos() const noexcept {
    return lv_spinbox_get_dec_point_pos(m_obj);
}

[[nodiscard]] uint32_t get_digit_count() const noexcept {
    return lv_spinbox_get_digit_count(m_obj);
}

[[nodiscard]] lv_dir_t get_digit_step_direction() const noexcept {
    return lv_spinbox_get_digit_step_direction(m_obj);
}

[[nodiscard]] int32_t get_max_value() const noexcept {
    return lv_spinbox_get_max_value(m_obj);
}

[[nodiscard]] int32_t get_min_value() const noexcept {
    return lv_spinbox_get_min_value(m_obj);
}

Spinbox& set_dec_point_pos(uint32_t dec_point_pos) noexcept {
    lv_spinbox_set_dec_point_pos(m_obj, dec_point_pos);
    return *this;
}

Spinbox& set_digit_count(uint32_t digit_count) noexcept {
    lv_spinbox_set_digit_count(m_obj, digit_count);
    return *this;
}

Spinbox& set_digit_step_direction(lv_dir_t direction) noexcept {
    lv_spinbox_set_digit_step_direction(m_obj, direction);
    return *this;
}

Spinbox& set_max_value(int32_t max_value) noexcept {
    lv_spinbox_set_max_value(m_obj, max_value);
    return *this;
}

Spinbox& set_min_value(int32_t min_value) noexcept {
    lv_spinbox_set_min_value(m_obj, min_value);
    return *this;
}

