// Auto-generated by gen_wrappers.py — do not edit
// Missing Table wrappers for LVGL C functions

Table& clear_cell_ctrl(uint32_t row, uint32_t col, lv_table_cell_ctrl_t ctrl) noexcept {
    lv_table_clear_cell_ctrl(m_obj, row, col, ctrl);
    return *this;
}

[[nodiscard]] void* get_cell_user_data(uint16_t row, uint16_t col) const noexcept {
    return lv_table_get_cell_user_data(m_obj, row, col);
}

Table& set_cell_user_data(uint16_t row, uint16_t col, void * user_data) noexcept {
    lv_table_set_cell_user_data(m_obj, row, col, user_data);
    return *this;
}

Table& set_selected_cell(uint16_t row, uint16_t col) noexcept {
    lv_table_set_selected_cell(m_obj, row, col);
    return *this;
}

