// Auto-generated by gen_wrappers.py — do not edit
// Missing Tabview wrappers for LVGL C functions

[[nodiscard]] lv_dir_t get_tab_bar_position() const noexcept {
    return lv_tabview_get_tab_bar_position(m_obj);
}

[[nodiscard]] lv_obj_t* get_tab_button(int32_t idx) const noexcept {
    return lv_tabview_get_tab_button(m_obj, idx);
}

Tabview& set_tab_text(uint32_t idx, const char * new_name) noexcept {
    lv_tabview_set_tab_text(m_obj, idx, new_name);
    return *this;
}

lv_obj_t* set_tab_translation_tag(const char * tag) noexcept {
    return lv_tabview_set_tab_translation_tag(m_obj, tag);
}

