// Auto-generated by gen_wrappers.py — do not edit
// Missing Textarea wrappers for LVGL C functions

Textarea& cursor_down() noexcept {
    lv_textarea_cursor_down(m_obj);
    return *this;
}

Textarea& cursor_left() noexcept {
    lv_textarea_cursor_left(m_obj);
    return *this;
}

Textarea& cursor_right() noexcept {
    lv_textarea_cursor_right(m_obj);
    return *this;
}

Textarea& cursor_up() noexcept {
    lv_textarea_cursor_up(m_obj);
    return *this;
}

[[nodiscard]] const char* get_accepted_chars() const noexcept {
    return lv_textarea_get_accepted_chars(m_obj);
}

[[nodiscard]] uint32_t get_current_char() const noexcept {
    return lv_textarea_get_current_char(m_obj);
}

[[nodiscard]] bool get_cursor_click_pos() const noexcept {
    return lv_textarea_get_cursor_click_pos(m_obj);
}

[[nodiscard]] lv_obj_t* get_label() const noexcept {
    return lv_textarea_get_label(m_obj);
}

[[nodiscard]] uint32_t get_max_length() const noexcept {
    return lv_textarea_get_max_length(m_obj);
}

[[nodiscard]] const char* get_password_bullet() const noexcept {
    return lv_textarea_get_password_bullet(m_obj);
}

[[nodiscard]] uint32_t get_password_show_time() const noexcept {
    return lv_textarea_get_password_show_time(m_obj);
}

Textarea& set_accepted_chars_static(const char * list) noexcept {
    lv_textarea_set_accepted_chars_static(m_obj, list);
    return *this;
}

Textarea& set_align(lv_text_align_t align) noexcept {
    lv_textarea_set_align(m_obj, align);
    return *this;
}

Textarea& set_insert_replace(const char * txt) noexcept {
    lv_textarea_set_insert_replace(m_obj, txt);
    return *this;
}

[[nodiscard]] bool text_is_selected() const noexcept {
    return lv_textarea_text_is_selected(m_obj);
}

