// Auto-generated by gen_wrappers.py — do not edit
// Missing Texture3D wrappers for LVGL C functions

Texture3D& set_flip(bool h_flip, bool v_flip) noexcept {
    lv_3dtexture_set_flip(m_obj, h_flip, v_flip);
    return *this;
}

Texture3D& set_src(lv_3dtexture_id_t id) noexcept {
    lv_3dtexture_set_src(m_obj, id);
    return *this;
}

