// Auto-generated by gen_wrappers.py — do not edit
// Missing Anim wrappers for LVGL C functions

bool custom_delete(lv_anim_custom_exec_cb_t exec_cb) noexcept {
    return lv_anim_custom_delete(&m_anim, exec_cb);
}

lv_anim_t* custom_get(lv_anim_custom_exec_cb_t exec_cb) noexcept {
    return lv_anim_custom_get(&m_anim, exec_cb);
}

[[nodiscard]] uint32_t get_delay() const noexcept {
    return lv_anim_get_delay(&m_anim);
}

[[nodiscard]] uint32_t get_playtime() const noexcept {
    return lv_anim_get_playtime(&m_anim);
}

[[nodiscard]] uint32_t get_repeat_count() const noexcept {
    return lv_anim_get_repeat_count(&m_anim);
}

[[nodiscard]] uint32_t get_time() const noexcept {
    return lv_anim_get_time(&m_anim);
}

[[nodiscard]] void* get_user_data() const noexcept {
    return lv_anim_get_user_data(&m_anim);
}

[[nodiscard]] int32_t path_bounce() const noexcept {
    return lv_anim_path_bounce(&m_anim);
}

[[nodiscard]] int32_t path_custom_bezier3() const noexcept {
    return lv_anim_path_custom_bezier3(&m_anim);
}

[[nodiscard]] int32_t path_ease_in() const noexcept {
    return lv_anim_path_ease_in(&m_anim);
}

[[nodiscard]] int32_t path_ease_in_out() const noexcept {
    return lv_anim_path_ease_in_out(&m_anim);
}

[[nodiscard]] int32_t path_ease_out() const noexcept {
    return lv_anim_path_ease_out(&m_anim);
}

[[nodiscard]] int32_t path_linear() const noexcept {
    return lv_anim_path_linear(&m_anim);
}

[[nodiscard]] int32_t path_overshoot() const noexcept {
    return lv_anim_path_overshoot(&m_anim);
}

[[nodiscard]] int32_t path_step() const noexcept {
    return lv_anim_path_step(&m_anim);
}

Anim& pause_for(uint32_t ms) noexcept {
    lv_anim_pause_for(&m_anim, ms);
    return *this;
}

Anim& set_bezier3_param(int16_t x1, int16_t y1, int16_t x2, int16_t y2) noexcept {
    lv_anim_set_bezier3_param(&m_anim, x1, y1, x2, y2);
    return *this;
}

Anim& set_custom_exec_cb(lv_anim_custom_exec_cb_t exec_cb) noexcept {
    lv_anim_set_custom_exec_cb(&m_anim, exec_cb);
    return *this;
}

Anim& set_get_value_cb(lv_anim_get_value_cb_t get_value_cb) noexcept {
    lv_anim_set_get_value_cb(&m_anim, get_value_cb);
    return *this;
}

Anim& set_reverse_delay(uint32_t delay) noexcept {
    lv_anim_set_reverse_delay(&m_anim, delay);
    return *this;
}

Anim& set_reverse_duration(uint32_t duration) noexcept {
    lv_anim_set_reverse_duration(&m_anim, duration);
    return *this;
}

Anim& set_reverse_time(uint32_t duration) noexcept {
    lv_anim_set_reverse_time(&m_anim, duration);
    return *this;
}

