// Auto-generated by gen_wrappers.py — do not edit
// Missing Display wrappers for LVGL C functions

Display& delete_refr_timer() noexcept {
    lv_display_delete_refr_timer(m_display);
    return *this;
}

[[nodiscard]] int32_t dpx(int32_t n) const noexcept {
    return lv_display_dpx(m_display, n);
}

Display& enable_invalidation(bool en) noexcept {
    lv_display_enable_invalidation(m_display, en);
    return *this;
}

LV_ATTRIBUTE_FLUSH_READY bool flush_is_last() noexcept {
    return lv_display_flush_is_last(m_display);
}

[[nodiscard]] bool get_antialiasing() const noexcept {
    return lv_display_get_antialiasing(m_display);
}

[[nodiscard]] lv_draw_buf_t* get_buf_active() const noexcept {
    return lv_display_get_buf_active(m_display);
}

[[nodiscard]] uint32_t get_draw_buf_size() const noexcept {
    return lv_display_get_draw_buf_size(m_display);
}

[[nodiscard]] void* get_driver_data() const noexcept {
    return lv_display_get_driver_data(m_display);
}

[[nodiscard]] uint32_t get_event_count() const noexcept {
    return lv_display_get_event_count(m_display);
}

[[nodiscard]] lv_event_dsc_t* get_event_dsc(uint32_t index) const noexcept {
    return lv_display_get_event_dsc(m_display, index);
}

[[nodiscard]] uint32_t get_inactive_time() const noexcept {
    return lv_display_get_inactive_time(m_display);
}

[[nodiscard]] uint32_t get_invalidated_draw_buf_size(uint32_t width, uint32_t height) const noexcept {
    return lv_display_get_invalidated_draw_buf_size(m_display, width, height);
}

[[nodiscard]] bool get_matrix_rotation() const noexcept {
    return lv_display_get_matrix_rotation(m_display);
}

[[nodiscard]] lv_display_t* get_next() const noexcept {
    return lv_display_get_next(m_display);
}

[[nodiscard]] int32_t get_offset_x() const noexcept {
    return lv_display_get_offset_x(m_display);
}

[[nodiscard]] int32_t get_offset_y() const noexcept {
    return lv_display_get_offset_y(m_display);
}

[[nodiscard]] int32_t get_original_horizontal_resolution() const noexcept {
    return lv_display_get_original_horizontal_resolution(m_display);
}

[[nodiscard]] int32_t get_original_vertical_resolution() const noexcept {
    return lv_display_get_original_vertical_resolution(m_display);
}

[[nodiscard]] int32_t get_physical_horizontal_resolution() const noexcept {
    return lv_display_get_physical_horizontal_resolution(m_display);
}

[[nodiscard]] int32_t get_physical_vertical_resolution() const noexcept {
    return lv_display_get_physical_vertical_resolution(m_display);
}

[[nodiscard]] lv_timer_t* get_refr_timer() const noexcept {
    return lv_display_get_refr_timer(m_display);
}

[[nodiscard]] lv_display_render_mode_t get_render_mode() const noexcept {
    return lv_display_get_render_mode(m_display);
}

[[nodiscard]] lv_obj_t* get_screen_loading() const noexcept {
    return lv_display_get_screen_loading(m_display);
}

[[nodiscard]] lv_obj_t* get_screen_prev() const noexcept {
    return lv_display_get_screen_prev(m_display);
}

[[nodiscard]] uint32_t get_tile_cnt() const noexcept {
    return lv_display_get_tile_cnt(m_display);
}

[[nodiscard]] void* get_user_data() const noexcept {
    return lv_display_get_user_data(m_display);
}

[[nodiscard]] bool is_double_buffered() const noexcept {
    return lv_display_is_double_buffered(m_display);
}

[[nodiscard]] bool is_invalidation_enabled() const noexcept {
    return lv_display_is_invalidation_enabled(m_display);
}

bool register_vsync_event(lv_event_cb_t event_cb, void * user_data) noexcept {
    return lv_display_register_vsync_event(m_display, event_cb, user_data);
}

bool remove_event(uint32_t index) noexcept {
    return lv_display_remove_event(m_display, index);
}

uint32_t remove_event_cb_with_user_data(lv_event_cb_t event_cb, void * user_data) noexcept {
    return lv_display_remove_event_cb_with_user_data(m_display, event_cb, user_data);
}

Display& rotate_area(lv_area_t * area) noexcept {
    lv_display_rotate_area(m_display, area);
    return *this;
}

lv_result_t send_event(lv_event_code_t code, void * param) noexcept {
    return lv_display_send_event(m_display, code, param);
}

lv_result_t send_vsync_event(void * param) noexcept {
    return lv_display_send_vsync_event(m_display, param);
}

Display& set_3rd_draw_buffer(lv_draw_buf_t * buf3) noexcept {
    lv_display_set_3rd_draw_buffer(m_display, buf3);
    return *this;
}

Display& set_antialiasing(bool en) noexcept {
    lv_display_set_antialiasing(m_display, en);
    return *this;
}

Display& set_buffers_with_stride(void * buf1, void * buf2, uint32_t buf_size, uint32_t stride, lv_display_render_mode_t render_mode) noexcept {
    lv_display_set_buffers_with_stride(m_display, buf1, buf2, buf_size, stride, render_mode);
    return *this;
}

Display& set_default() noexcept {
    lv_display_set_default(m_display);
    return *this;
}

Display& set_draw_buffers(lv_draw_buf_t * buf1, lv_draw_buf_t * buf2) noexcept {
    lv_display_set_draw_buffers(m_display, buf1, buf2);
    return *this;
}

Display& set_driver_data(void * driver_data) noexcept {
    lv_display_set_driver_data(m_display, driver_data);
    return *this;
}

Display& set_flush_wait_cb(lv_display_flush_wait_cb_t wait_cb) noexcept {
    lv_display_set_flush_wait_cb(m_display, wait_cb);
    return *this;
}

Display& set_matrix_rotation(bool enable) noexcept {
    lv_display_set_matrix_rotation(m_display, enable);
    return *this;
}

Display& set_offset(int32_t x, int32_t y) noexcept {
    lv_display_set_offset(m_display, x, y);
    return *this;
}

Display& set_physical_resolution(int32_t hor_res, int32_t ver_res) noexcept {
    lv_display_set_physical_resolution(m_display, hor_res, ver_res);
    return *this;
}

Display& set_render_mode(lv_display_render_mode_t render_mode) noexcept {
    lv_display_set_render_mode(m_display, render_mode);
    return *this;
}

Display& set_resolution(int32_t hor_res, int32_t ver_res) noexcept {
    lv_display_set_resolution(m_display, hor_res, ver_res);
    return *this;
}

Display& set_sync_cb(lv_display_sync_cb_t sync_cb) noexcept {
    lv_display_set_sync_cb(m_display, sync_cb);
    return *this;
}

Display& set_sync_wait_cb(lv_display_sync_wait_cb_t wait_cb) noexcept {
    lv_display_set_sync_wait_cb(m_display, wait_cb);
    return *this;
}

Display& set_tile_cnt(uint32_t tile_cnt) noexcept {
    lv_display_set_tile_cnt(m_display, tile_cnt);
    return *this;
}

Display& set_user_data(void * user_data) noexcept {
    lv_display_set_user_data(m_display, user_data);
    return *this;
}

LV_ATTRIBUTE_SYNC_READY bool sync_is_last() noexcept {
    return lv_display_sync_is_last(m_display);
}

LV_ATTRIBUTE_SYNC_READY void sync_ready() noexcept {
    return lv_display_sync_ready(m_display);
}

Display& trigger_activity() noexcept {
    lv_display_trigger_activity(m_display);
    return *this;
}

bool unregister_vsync_event(lv_event_cb_t event_cb, void * user_data) noexcept {
    return lv_display_unregister_vsync_event(m_display, event_cb, user_data);
}

