// Auto-generated by gen_wrappers.py — do not edit
// Missing Group wrappers for LVGL C functions

Group& focus_freeze(bool en) noexcept {
    lv_group_focus_freeze(m_group, en);
    return *this;
}

[[nodiscard]] lv_group_edge_cb_t get_edge_cb() const noexcept {
    return lv_group_get_edge_cb(m_group);
}

[[nodiscard]] lv_group_focus_cb_t get_focus_cb() const noexcept {
    return lv_group_get_focus_cb(m_group);
}

[[nodiscard]] lv_obj_t* get_obj_by_index(uint32_t index) const noexcept {
    return lv_group_get_obj_by_index(m_group, index);
}

Group& set_edge_cb(lv_group_edge_cb_t edge_cb) noexcept {
    lv_group_set_edge_cb(m_group, edge_cb);
    return *this;
}

Group& set_focus_cb(lv_group_focus_cb_t focus_cb) noexcept {
    lv_group_set_focus_cb(m_group, focus_cb);
    return *this;
}

Group& set_refocus_policy(lv_group_refocus_policy_t policy) noexcept {
    lv_group_set_refocus_policy(m_group, policy);
    return *this;
}

