// Auto-generated by gen_wrappers.py — do not edit
// Missing Indev wrappers for LVGL C functions

lv_event_dsc_t* add_event_cb(lv_event_cb_t event_cb, lv_event_code_t filter, void * user_data) noexcept {
    return lv_indev_add_event_cb(m_indev, event_cb, filter, user_data);
}

[[nodiscard]] lv_obj_t* get_cursor() const noexcept {
    return lv_indev_get_cursor(m_indev);
}

[[nodiscard]] lv_display_t* get_display() const noexcept {
    return lv_indev_get_display(m_indev);
}

[[nodiscard]] void* get_driver_data() const noexcept {
    return lv_indev_get_driver_data(m_indev);
}

[[nodiscard]] uint32_t get_event_count() const noexcept {
    return lv_indev_get_event_count(m_indev);
}

[[nodiscard]] lv_event_dsc_t* get_event_dsc(uint32_t index) const noexcept {
    return lv_indev_get_event_dsc(m_indev, index);
}

[[nodiscard]] lv_indev_mode_t get_mode() const noexcept {
    return lv_indev_get_mode(m_indev);
}

[[nodiscard]] bool get_press_moved() const noexcept {
    return lv_indev_get_press_moved(m_indev);
}

[[nodiscard]] lv_indev_read_cb_t get_read_cb() const noexcept {
    return lv_indev_get_read_cb(m_indev);
}

[[nodiscard]] lv_timer_t* get_read_timer() const noexcept {
    return lv_indev_get_read_timer(m_indev);
}

[[nodiscard]] uint8_t get_short_click_streak() const noexcept {
    return lv_indev_get_short_click_streak(m_indev);
}

[[nodiscard]] lv_indev_state_t get_state() const noexcept {
    return lv_indev_get_state(m_indev);
}

Indev& read() noexcept {
    lv_indev_read(m_indev);
    return *this;
}

bool remove_event(uint32_t index) noexcept {
    return lv_indev_remove_event(m_indev, index);
}

uint32_t remove_event_cb_with_user_data(lv_event_cb_t event_cb, void * user_data) noexcept {
    return lv_indev_remove_event_cb_with_user_data(m_indev, event_cb, user_data);
}

Indev& reset(lv_obj_t * obj) noexcept {
    lv_indev_reset(m_indev, obj);
    return *this;
}

Indev& reset_long_press() noexcept {
    lv_indev_reset_long_press(m_indev);
    return *this;
}

lv_result_t send_event(lv_event_code_t code, void * param) noexcept {
    return lv_indev_send_event(m_indev, code, param);
}

Indev& set_driver_data(void * driver_data) noexcept {
    lv_indev_set_driver_data(m_indev, driver_data);
    return *this;
}

Indev& set_mode(lv_indev_mode_t mode) noexcept {
    lv_indev_set_mode(m_indev, mode);
    return *this;
}

Indev& stop_processing() noexcept {
    lv_indev_stop_processing(m_indev);
    return *this;
}

Indev& wait_release() noexcept {
    lv_indev_wait_release(m_indev);
    return *this;
}

