// Auto-generated by gen_wrappers.py — do not edit
// Missing ObjectMixin wrappers for LVGL C functions

lv_result_t add_child(lv_obj_t * child) noexcept {
    return lv_obj_add_child(obj(), child);
}

Derived& add_play_timeline_event(lv_event_code_t trigger, lv_anim_timeline_t * at, uint32_t delay, bool reverse) noexcept {
    lv_obj_add_play_timeline_event(obj(), trigger, at, delay, reverse);
    return *static_cast<Derived*>(this);
}

Derived& add_screen_create_event(lv_event_code_t trigger, lv_screen_create_cb_t screen_create_cb, lv_screen_load_anim_t anim_type, uint32_t duration, uint32_t delay) noexcept {
    lv_obj_add_screen_create_event(obj(), trigger, screen_create_cb, anim_type, duration, delay);
    return *static_cast<Derived*>(this);
}

Derived& add_screen_load_event(lv_event_code_t trigger, lv_obj_t * screen, lv_screen_load_anim_t anim_type, uint32_t duration, uint32_t delay) noexcept {
    lv_obj_add_screen_load_event(obj(), trigger, screen, anim_type, duration, delay);
    return *static_cast<Derived*>(this);
}

lv_subject_increment_dsc_t* add_subject_increment_event(lv_subject_t * subject, lv_event_code_t trigger, int32_t step) noexcept {
    return lv_obj_add_subject_increment_event(obj(), subject, trigger, step);
}

Derived& add_subject_set_float_event(lv_subject_t * subject, lv_event_code_t trigger, float value) noexcept {
    lv_obj_add_subject_set_float_event(obj(), subject, trigger, value);
    return *static_cast<Derived*>(this);
}

Derived& add_subject_set_int_event(lv_subject_t * subject, lv_event_code_t trigger, int32_t value) noexcept {
    lv_obj_add_subject_set_int_event(obj(), subject, trigger, value);
    return *static_cast<Derived*>(this);
}

Derived& add_subject_set_string_event(lv_subject_t * subject, lv_event_code_t trigger, const char * value) noexcept {
    lv_obj_add_subject_set_string_event(obj(), subject, trigger, value);
    return *static_cast<Derived*>(this);
}

Derived& add_subject_toggle_event(lv_subject_t * subject, lv_event_code_t trigger) noexcept {
    lv_obj_add_subject_toggle_event(obj(), subject, trigger);
    return *static_cast<Derived*>(this);
}

[[nodiscard]] bool area_is_visible(lv_area_t * area) const noexcept {
    return lv_obj_area_is_visible(obj(), area);
}

lv_observer_t* bind_flag_if_eq(lv_subject_t * subject, lv_obj_flag_t flag, int32_t ref_value) noexcept {
    return lv_obj_bind_flag_if_eq(obj(), subject, flag, ref_value);
}

lv_observer_t* bind_flag_if_ge(lv_subject_t * subject, lv_obj_flag_t flag, int32_t ref_value) noexcept {
    return lv_obj_bind_flag_if_ge(obj(), subject, flag, ref_value);
}

lv_observer_t* bind_flag_if_gt(lv_subject_t * subject, lv_obj_flag_t flag, int32_t ref_value) noexcept {
    return lv_obj_bind_flag_if_gt(obj(), subject, flag, ref_value);
}

lv_observer_t* bind_flag_if_le(lv_subject_t * subject, lv_obj_flag_t flag, int32_t ref_value) noexcept {
    return lv_obj_bind_flag_if_le(obj(), subject, flag, ref_value);
}

lv_observer_t* bind_flag_if_lt(lv_subject_t * subject, lv_obj_flag_t flag, int32_t ref_value) noexcept {
    return lv_obj_bind_flag_if_lt(obj(), subject, flag, ref_value);
}

lv_observer_t* bind_flag_if_not_eq(lv_subject_t * subject, lv_obj_flag_t flag, int32_t ref_value) noexcept {
    return lv_obj_bind_flag_if_not_eq(obj(), subject, flag, ref_value);
}

lv_observer_t* bind_state_if_eq(lv_subject_t * subject, lv_state_t state, int32_t ref_value) noexcept {
    return lv_obj_bind_state_if_eq(obj(), subject, state, ref_value);
}

lv_observer_t* bind_state_if_ge(lv_subject_t * subject, lv_state_t state, int32_t ref_value) noexcept {
    return lv_obj_bind_state_if_ge(obj(), subject, state, ref_value);
}

lv_observer_t* bind_state_if_gt(lv_subject_t * subject, lv_state_t state, int32_t ref_value) noexcept {
    return lv_obj_bind_state_if_gt(obj(), subject, state, ref_value);
}

lv_observer_t* bind_state_if_le(lv_subject_t * subject, lv_state_t state, int32_t ref_value) noexcept {
    return lv_obj_bind_state_if_le(obj(), subject, state, ref_value);
}

lv_observer_t* bind_state_if_lt(lv_subject_t * subject, lv_state_t state, int32_t ref_value) noexcept {
    return lv_obj_bind_state_if_lt(obj(), subject, state, ref_value);
}

lv_observer_t* bind_state_if_not_eq(lv_subject_t * subject, lv_state_t state, int32_t ref_value) noexcept {
    return lv_obj_bind_state_if_not_eq(obj(), subject, state, ref_value);
}

lv_observer_t* bind_style(const lv_style_t * style, lv_style_selector_t selector, lv_subject_t * subject, int32_t ref_value) noexcept {
    return lv_obj_bind_style(obj(), style, selector, subject, ref_value);
}

[[nodiscard]] lv_text_align_t calculate_style_text_align(lv_part_t part, const char * txt) const noexcept {
    return lv_obj_calculate_style_text_align(obj(), part, txt);
}

Derived& class_init_obj() noexcept {
    lv_obj_class_init_obj(obj());
    return *static_cast<Derived*>(this);
}

Derived& delete_async() noexcept {
    lv_obj_delete_async(obj());
    return *static_cast<Derived*>(this);
}

Derived& delete_delayed(uint32_t delay_ms) noexcept {
    lv_obj_delete_delayed(obj(), delay_ms);
    return *static_cast<Derived*>(this);
}

Derived& destruct() noexcept {
    lv_obj_destruct(obj());
    return *static_cast<Derived*>(this);
}

Derived& dump_tree() noexcept {
    lv_obj_dump_tree(obj());
    return *static_cast<Derived*>(this);
}

Derived& fade_in(uint32_t time, uint32_t delay) noexcept {
    lv_obj_fade_in(obj(), time, delay);
    return *static_cast<Derived*>(this);
}

Derived& fade_out(uint32_t time, uint32_t delay) noexcept {
    lv_obj_fade_out(obj(), time, delay);
    return *static_cast<Derived*>(this);
}

[[nodiscard]] lv_obj_t* find_by_id(const void * id) const noexcept {
    return lv_obj_find_by_id(obj(), id);
}

void get_click_area(lv_area_t * area) const noexcept {
    lv_obj_get_click_area(obj(), area);
}

void get_content_coords(lv_area_t * area) const noexcept {
    lv_obj_get_content_coords(obj(), area);
}

[[nodiscard]] int32_t get_ext_draw_size() const noexcept {
    return lv_obj_get_ext_draw_size(obj());
}

[[nodiscard]] lv_group_t* get_group() const noexcept {
    return lv_obj_get_group(obj());
}

[[nodiscard]] void* get_id() const noexcept {
    return lv_obj_get_id(obj());
}

[[nodiscard]] lv_layer_type_t get_layer_type() const noexcept {
    return lv_obj_get_layer_type(obj());
}

[[nodiscard]] int32_t get_scroll_bottom() const noexcept {
    return lv_obj_get_scroll_bottom(obj());
}

[[nodiscard]] lv_dir_t get_scroll_dir() const noexcept {
    return lv_obj_get_scroll_dir(obj());
}

void get_scroll_end(lv_point_t * end) const noexcept {
    lv_obj_get_scroll_end(obj(), end);
}

[[nodiscard]] int32_t get_scroll_left() const noexcept {
    return lv_obj_get_scroll_left(obj());
}

[[nodiscard]] int32_t get_scroll_right() const noexcept {
    return lv_obj_get_scroll_right(obj());
}

[[nodiscard]] lv_scroll_snap_t get_scroll_snap_x() const noexcept {
    return lv_obj_get_scroll_snap_x(obj());
}

[[nodiscard]] lv_scroll_snap_t get_scroll_snap_y() const noexcept {
    return lv_obj_get_scroll_snap_y(obj());
}

[[nodiscard]] int32_t get_scroll_top() const noexcept {
    return lv_obj_get_scroll_top(obj());
}

void get_scrollbar_area(lv_area_t * hor, lv_area_t * ver) const noexcept {
    lv_obj_get_scrollbar_area(obj(), hor, ver);
}

[[nodiscard]] lv_scrollbar_mode_t get_scrollbar_mode() const noexcept {
    return lv_obj_get_scrollbar_mode(obj());
}

[[nodiscard]] int32_t get_self_height() const noexcept {
    return lv_obj_get_self_height(obj());
}

[[nodiscard]] int32_t get_self_width() const noexcept {
    return lv_obj_get_self_width(obj());
}

[[nodiscard]] const lv_matrix_t* get_transform() const noexcept {
    return lv_obj_get_transform(obj());
}

void get_transformed_area(lv_area_t * area, lv_obj_point_transform_flag_t flags) const noexcept {
    lv_obj_get_transformed_area(obj(), area, flags);
}

[[nodiscard]] int32_t get_x2() const noexcept {
    return lv_obj_get_x2(obj());
}

[[nodiscard]] int32_t get_x_aligned() const noexcept {
    return lv_obj_get_x_aligned(obj());
}

[[nodiscard]] int32_t get_y2() const noexcept {
    return lv_obj_get_y2(obj());
}

[[nodiscard]] int32_t get_y_aligned() const noexcept {
    return lv_obj_get_y_aligned(obj());
}

[[nodiscard]] bool has_flag_any(lv_obj_flag_t f) const noexcept {
    return lv_obj_has_flag_any(obj(), f);
}

bool hit_test(const lv_point_t * point) noexcept {
    return lv_obj_hit_test(obj(), point);
}

Derived& init_draw_blur_dsc(lv_part_t part, lv_draw_blur_dsc_t * draw_dsc) noexcept {
    lv_obj_init_draw_blur_dsc(obj(), part, draw_dsc);
    return *static_cast<Derived*>(this);
}

[[nodiscard]] lv_result_t invalidate_area(const lv_area_t * area) const noexcept {
    return lv_obj_invalidate_area(obj(), area);
}

[[nodiscard]] bool is_editable() const noexcept {
    return lv_obj_is_editable(obj());
}

[[nodiscard]] bool is_group_def() const noexcept {
    return lv_obj_is_group_def(obj());
}

[[nodiscard]] bool is_height_max() const noexcept {
    return lv_obj_is_height_max(obj());
}

[[nodiscard]] bool is_height_min() const noexcept {
    return lv_obj_is_height_min(obj());
}

[[nodiscard]] bool is_layout_positioned() const noexcept {
    return lv_obj_is_layout_positioned(obj());
}

[[nodiscard]] bool is_scrolling() const noexcept {
    return lv_obj_is_scrolling(obj());
}

[[nodiscard]] bool is_style_any_height_content() const noexcept {
    return lv_obj_is_style_any_height_content(obj());
}

[[nodiscard]] bool is_style_any_width_content() const noexcept {
    return lv_obj_is_style_any_width_content(obj());
}

[[nodiscard]] bool is_valid() const noexcept {
    return lv_obj_is_valid(obj());
}

[[nodiscard]] bool is_visible() const noexcept {
    return lv_obj_is_visible(obj());
}

[[nodiscard]] bool is_width_max() const noexcept {
    return lv_obj_is_width_max(obj());
}

[[nodiscard]] bool is_width_min() const noexcept {
    return lv_obj_is_width_min(obj());
}

Derived& mark_layout_as_dirty() noexcept {
    lv_obj_mark_layout_as_dirty(obj());
    return *static_cast<Derived*>(this);
}

Derived& move_children_by(int32_t x_diff, int32_t y_diff, bool ignore_floating) noexcept {
    lv_obj_move_children_by(obj(), x_diff, y_diff, ignore_floating);
    return *static_cast<Derived*>(this);
}

Derived& move_to(int32_t x, int32_t y) noexcept {
    lv_obj_move_to(obj(), x, y);
    return *static_cast<Derived*>(this);
}

Derived& null_on_delete() noexcept {
    lv_obj_null_on_delete(obj());
    return *static_cast<Derived*>(this);
}

[[nodiscard]] lv_prop_id_t property_get_id(const char * name) const noexcept {
    return lv_obj_property_get_id(obj(), name);
}

Derived& readjust_scroll(lv_anim_enable_t anim_en) noexcept {
    lv_obj_readjust_scroll(obj(), anim_en);
    return *static_cast<Derived*>(this);
}

Derived& refr_pos() noexcept {
    lv_obj_refr_pos(obj());
    return *static_cast<Derived*>(this);
}

bool refr_size() noexcept {
    return lv_obj_refr_size(obj());
}

bool refresh_self_size() noexcept {
    return lv_obj_refresh_self_size(obj());
}

Derived& remove_child(lv_obj_t * child) noexcept {
    lv_obj_remove_child(obj(), child);
    return *static_cast<Derived*>(this);
}

Derived& remove_from_subject(lv_subject_t * subject) noexcept {
    lv_obj_remove_from_subject(obj(), subject);
    return *static_cast<Derived*>(this);
}

bool replace_style(const lv_style_t * old_style, const lv_style_t * new_style, lv_style_selector_t selector) noexcept {
    return lv_obj_replace_style(obj(), old_style, new_style, selector);
}

Derived& reset_transform() noexcept {
    lv_obj_reset_transform(obj());
    return *static_cast<Derived*>(this);
}

Derived& scroll_by_bounded(int32_t dx, int32_t dy, lv_anim_enable_t anim_en) noexcept {
    lv_obj_scroll_by_bounded(obj(), dx, dy, anim_en);
    return *static_cast<Derived*>(this);
}

lv_result_t scroll_by_raw(int32_t x, int32_t y) noexcept {
    return lv_obj_scroll_by_raw(obj(), x, y);
}

Derived& scroll_to_view(lv_anim_enable_t anim_en) noexcept {
    lv_obj_scroll_to_view(obj(), anim_en);
    return *static_cast<Derived*>(this);
}

Derived& scroll_to_view_recursive(lv_anim_enable_t anim_en) noexcept {
    lv_obj_scroll_to_view_recursive(obj(), anim_en);
    return *static_cast<Derived*>(this);
}

Derived& scrollbar_invalidate() noexcept {
    lv_obj_scrollbar_invalidate(obj());
    return *static_cast<Derived*>(this);
}

Derived& set_content_height(int32_t h) noexcept {
    lv_obj_set_content_height(obj(), h);
    return *static_cast<Derived*>(this);
}

Derived& set_content_width(int32_t w) noexcept {
    lv_obj_set_content_width(obj(), w);
    return *static_cast<Derived*>(this);
}

Derived& set_flag(lv_obj_flag_t f, bool v) noexcept {
    lv_obj_set_flag(obj(), f, v);
    return *static_cast<Derived*>(this);
}

Derived& set_id(void * id) noexcept {
    lv_obj_set_id(obj(), id);
    return *static_cast<Derived*>(this);
}

Derived& set_name_static(const char * name) noexcept {
    lv_obj_set_name_static(obj(), name);
    return *static_cast<Derived*>(this);
}

Derived& set_state(lv_state_t state, bool v) noexcept {
    lv_obj_set_state(obj(), state, v);
    return *static_cast<Derived*>(this);
}

Derived& set_subject_increment_event_max_value(lv_subject_increment_dsc_t * dsc, int32_t max_value) noexcept {
    lv_obj_set_subject_increment_event_max_value(obj(), dsc, max_value);
    return *static_cast<Derived*>(this);
}

Derived& set_subject_increment_event_min_value(lv_subject_increment_dsc_t * dsc, int32_t min_value) noexcept {
    lv_obj_set_subject_increment_event_min_value(obj(), dsc, min_value);
    return *static_cast<Derived*>(this);
}

Derived& set_subject_increment_event_rollover(lv_subject_increment_dsc_t * dsc, bool rollover) noexcept {
    lv_obj_set_subject_increment_event_rollover(obj(), dsc, rollover);
    return *static_cast<Derived*>(this);
}

Derived& set_transform(const lv_matrix_t * matrix) noexcept {
    lv_obj_set_transform(obj(), matrix);
    return *static_cast<Derived*>(this);
}

void stop_scroll_anim() const noexcept {
    lv_obj_stop_scroll_anim(obj());
}

[[nodiscard]] lv_color32_t style_apply_recolor(lv_part_t part, lv_color32_t color) const noexcept {
    return lv_obj_style_apply_recolor(obj(), part, color);
}

Derived& style_create_transition(lv_part_t part, lv_state_t prev_state, lv_state_t new_state, const lv_obj_style_transition_dsc_t * tr) noexcept {
    lv_obj_style_create_transition(obj(), part, prev_state, new_state, tr);
    return *static_cast<Derived*>(this);
}

bool style_get_disabled(const lv_style_t * style, lv_style_selector_t selector) noexcept {
    return lv_obj_style_get_disabled(obj(), style, selector);
}

Derived& style_set_disabled(const lv_style_t * style, lv_style_selector_t selector, bool dis) noexcept {
    lv_obj_style_set_disabled(obj(), style, selector, dis);
    return *static_cast<Derived*>(this);
}

lv_style_state_cmp_t style_state_compare(lv_state_t state1, lv_state_t state2) noexcept {
    return lv_obj_style_state_compare(obj(), state1, state2);
}

void transform_point(lv_point_t * p, lv_obj_point_transform_flag_t flags) const noexcept {
    lv_obj_transform_point(obj(), p, flags);
}

Derived& tree_walk(lv_obj_tree_walk_cb_t cb, void * user_data) noexcept {
    lv_obj_tree_walk(obj(), cb, user_data);
    return *static_cast<Derived*>(this);
}

Derived& update_layer_type() noexcept {
    lv_obj_update_layer_type(obj());
    return *static_cast<Derived*>(this);
}

