// Auto-generated by gen_wrappers.py — do not edit
// Missing State wrappers for LVGL C functions

lv_observer_t* add_observer_with_target(lv_observer_cb_t observer_cb, void * target, void * user_data) noexcept {
    return lv_subject_add_observer_with_target(&m_subject, observer_cb, target, user_data);
}

State& copy_string(const char * buf) noexcept {
    lv_subject_copy_string(&m_subject, buf);
    return *this;
}

[[nodiscard]] float get_float() const noexcept {
    return lv_subject_get_float(&m_subject);
}

[[nodiscard]] lv_subject_t* get_group_element(int32_t index) const noexcept {
    return lv_subject_get_group_element(&m_subject, index);
}

[[nodiscard]] lv_color_t get_previous_color() const noexcept {
    return lv_subject_get_previous_color(&m_subject);
}

[[nodiscard]] float get_previous_float() const noexcept {
    return lv_subject_get_previous_float(&m_subject);
}

[[nodiscard]] int32_t get_previous_int() const noexcept {
    return lv_subject_get_previous_int(&m_subject);
}

[[nodiscard]] const void* get_previous_pointer() const noexcept {
    return lv_subject_get_previous_pointer(&m_subject);
}

[[nodiscard]] const char* get_previous_string() const noexcept {
    return lv_subject_get_previous_string(&m_subject);
}

[[nodiscard]] const char* get_string() const noexcept {
    return lv_subject_get_string(&m_subject);
}

State& init_float(float value) noexcept {
    lv_subject_init_float(&m_subject, value);
    return *this;
}

State& init_string(char * buf, char * prev_buf, size_t size, const char * value) noexcept {
    lv_subject_init_string(&m_subject, buf, prev_buf, size, value);
    return *this;
}

State& set_float(float value) noexcept {
    lv_subject_set_float(&m_subject, value);
    return *this;
}

State& set_max_value_float(float max_value) noexcept {
    lv_subject_set_max_value_float(&m_subject, max_value);
    return *this;
}

State& set_max_value_int(int32_t max_value) noexcept {
    lv_subject_set_max_value_int(&m_subject, max_value);
    return *this;
}

State& set_min_value_float(float min_value) noexcept {
    lv_subject_set_min_value_float(&m_subject, min_value);
    return *this;
}

State& set_min_value_int(int32_t min_value) noexcept {
    lv_subject_set_min_value_int(&m_subject, min_value);
    return *this;
}

