// Auto-generated by gen_wrappers.py — do not edit
// Missing StyleMixin wrappers for LVGL C functions

Derived& anim(const lv_anim_t * value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_anim(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& arc_image_src(const void * value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_arc_image_src(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& base_dir(lv_base_dir_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_base_dir(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& bg_grad_opa(lv_opa_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_bg_grad_opa(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& bg_image_opa(lv_opa_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_bg_image_opa(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& bg_image_recolor(lv_color_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_bg_image_recolor(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& bg_image_recolor_opa(lv_opa_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_bg_image_recolor_opa(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& bg_image_tiled(bool value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_bg_image_tiled(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& bg_main_opa(lv_opa_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_bg_main_opa(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& bg_main_stop(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_bg_main_stop(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& blur_backdrop(bool value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_blur_backdrop(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& blur_quality(lv_blur_quality_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_blur_quality(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& blur_radius(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_blur_radius(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& border_post(bool value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_border_post(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

int32_t clamped_height() noexcept {
    return lv_obj_get_style_clamped_height(obj());
}

int32_t clamped_width() noexcept {
    return lv_obj_get_style_clamped_width(obj());
}

Derived& clip_corner(bool value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_clip_corner(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& color_filter_dsc(const lv_color_filter_dsc_t * value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_color_filter_dsc(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& color_filter_opa(lv_opa_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_color_filter_opa(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& drop_shadow_color(lv_color_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_drop_shadow_color(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& drop_shadow_offset_x(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_drop_shadow_offset_x(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& drop_shadow_offset_y(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_drop_shadow_offset_y(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& drop_shadow_opa(lv_opa_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_drop_shadow_opa(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& drop_shadow_quality(lv_blur_quality_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_drop_shadow_quality(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& drop_shadow_radius(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_drop_shadow_radius(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& flex_grow(uint8_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_flex_grow(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& grid_cell_column_pos(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_grid_cell_column_pos(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& grid_cell_column_span(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_grid_cell_column_span(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& grid_cell_row_pos(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_grid_cell_row_pos(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& grid_cell_row_span(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_grid_cell_row_span(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& grid_cell_x_align(lv_grid_align_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_grid_cell_x_align(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& grid_cell_y_align(lv_grid_align_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_grid_cell_y_align(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& image_colorkey(const lv_image_colorkey_t * value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_image_colorkey(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& length(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_length(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& line_dash_gap(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_line_dash_gap(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& line_dash_width(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_line_dash_width(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& opa_layered(lv_opa_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_opa_layered(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

[[nodiscard]] lv_opa_t opa_recursive(lv_part_t part) const noexcept {
    return lv_obj_get_style_opa_recursive(obj(), part);
}

Derived& pad_radial(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_pad_radial(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& radial_offset(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_radial_offset(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& recolor(lv_color_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_recolor(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& recolor_opa(lv_opa_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_recolor_opa(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

[[nodiscard]] lv_color32_t recolor_recursive(lv_part_t part) const noexcept {
    return lv_obj_get_style_recolor_recursive(obj(), part);
}

Derived& rotary_sensitivity(uint32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_rotary_sensitivity(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& style_align(lv_align_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_align(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& style_flex_flow(lv_flex_flow_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_flex_flow(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& style_layout(uint16_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_layout(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& style_x(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_x(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& style_y(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_y(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& text_decor(lv_text_decor_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_text_decor(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& text_opa(lv_opa_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_text_opa(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& text_outline_stroke_color(lv_color_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_text_outline_stroke_color(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& text_outline_stroke_opa(lv_opa_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_text_outline_stroke_opa(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& text_outline_stroke_width(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_text_outline_stroke_width(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& transform_skew_x(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_transform_skew_x(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& transform_skew_y(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_transform_skew_y(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

Derived& translate_radial(int32_t value, lv_style_selector_t selector) noexcept {
    lv_obj_set_style_translate_radial(obj(), value, selector);
    return *static_cast<Derived*>(this);
}

