// Auto-generated by gen_wrappers.py — do not edit
// Missing Style wrappers for LVGL C functions

[[nodiscard]] bool is_empty() const noexcept {
    return lv_style_is_empty(&m_style);
}

Style& merge(const lv_style_t * src) noexcept {
    lv_style_merge(&m_style, src);
    return *this;
}

Style& set_anim(const lv_anim_t * value) noexcept {
    lv_style_set_anim(&m_style, value);
    return *this;
}

Style& set_anim_duration(uint32_t value) noexcept {
    lv_style_set_anim_duration(&m_style, value);
    return *this;
}

Style& set_arc_image_src(const void * value) noexcept {
    lv_style_set_arc_image_src(&m_style, value);
    return *this;
}

Style& set_base_dir(lv_base_dir_t value) noexcept {
    lv_style_set_base_dir(&m_style, value);
    return *this;
}

Style& set_bg_grad(const lv_grad_dsc_t * value) noexcept {
    lv_style_set_bg_grad(&m_style, value);
    return *this;
}

Style& set_bg_grad_opa(lv_opa_t value) noexcept {
    lv_style_set_bg_grad_opa(&m_style, value);
    return *this;
}

Style& set_bg_image_opa(lv_opa_t value) noexcept {
    lv_style_set_bg_image_opa(&m_style, value);
    return *this;
}

Style& set_bg_image_recolor(lv_color_t value) noexcept {
    lv_style_set_bg_image_recolor(&m_style, value);
    return *this;
}

Style& set_bg_image_recolor_opa(lv_opa_t value) noexcept {
    lv_style_set_bg_image_recolor_opa(&m_style, value);
    return *this;
}

Style& set_bg_image_src(const void * value) noexcept {
    lv_style_set_bg_image_src(&m_style, value);
    return *this;
}

Style& set_bg_image_tiled(bool value) noexcept {
    lv_style_set_bg_image_tiled(&m_style, value);
    return *this;
}

Style& set_bg_main_opa(lv_opa_t value) noexcept {
    lv_style_set_bg_main_opa(&m_style, value);
    return *this;
}

Style& set_bitmap_mask_src(const void * value) noexcept {
    lv_style_set_bitmap_mask_src(&m_style, value);
    return *this;
}

Style& set_blur_backdrop(bool value) noexcept {
    lv_style_set_blur_backdrop(&m_style, value);
    return *this;
}

Style& set_blur_quality(lv_blur_quality_t value) noexcept {
    lv_style_set_blur_quality(&m_style, value);
    return *this;
}

Style& set_blur_radius(int32_t value) noexcept {
    lv_style_set_blur_radius(&m_style, value);
    return *this;
}

Style& set_border_post(bool value) noexcept {
    lv_style_set_border_post(&m_style, value);
    return *this;
}

Style& set_color_filter_dsc(const lv_color_filter_dsc_t * value) noexcept {
    lv_style_set_color_filter_dsc(&m_style, value);
    return *this;
}

Style& set_color_filter_opa(lv_opa_t value) noexcept {
    lv_style_set_color_filter_opa(&m_style, value);
    return *this;
}

Style& set_drop_shadow_color(lv_color_t value) noexcept {
    lv_style_set_drop_shadow_color(&m_style, value);
    return *this;
}

Style& set_drop_shadow_offset_x(int32_t value) noexcept {
    lv_style_set_drop_shadow_offset_x(&m_style, value);
    return *this;
}

Style& set_drop_shadow_offset_y(int32_t value) noexcept {
    lv_style_set_drop_shadow_offset_y(&m_style, value);
    return *this;
}

Style& set_drop_shadow_opa(lv_opa_t value) noexcept {
    lv_style_set_drop_shadow_opa(&m_style, value);
    return *this;
}

Style& set_drop_shadow_quality(lv_blur_quality_t value) noexcept {
    lv_style_set_drop_shadow_quality(&m_style, value);
    return *this;
}

Style& set_drop_shadow_radius(int32_t value) noexcept {
    lv_style_set_drop_shadow_radius(&m_style, value);
    return *this;
}

Style& set_grid_cell_column_pos(int32_t value) noexcept {
    lv_style_set_grid_cell_column_pos(&m_style, value);
    return *this;
}

Style& set_grid_cell_column_span(int32_t value) noexcept {
    lv_style_set_grid_cell_column_span(&m_style, value);
    return *this;
}

Style& set_grid_cell_row_pos(int32_t value) noexcept {
    lv_style_set_grid_cell_row_pos(&m_style, value);
    return *this;
}

Style& set_grid_cell_row_span(int32_t value) noexcept {
    lv_style_set_grid_cell_row_span(&m_style, value);
    return *this;
}

Style& set_grid_cell_x_align(lv_grid_align_t value) noexcept {
    lv_style_set_grid_cell_x_align(&m_style, value);
    return *this;
}

Style& set_grid_cell_y_align(lv_grid_align_t value) noexcept {
    lv_style_set_grid_cell_y_align(&m_style, value);
    return *this;
}

Style& set_grid_column_align(lv_grid_align_t value) noexcept {
    lv_style_set_grid_column_align(&m_style, value);
    return *this;
}

Style& set_grid_column_dsc_array(const int32_t * value) noexcept {
    lv_style_set_grid_column_dsc_array(&m_style, value);
    return *this;
}

Style& set_grid_row_align(lv_grid_align_t value) noexcept {
    lv_style_set_grid_row_align(&m_style, value);
    return *this;
}

Style& set_grid_row_dsc_array(const int32_t * value) noexcept {
    lv_style_set_grid_row_dsc_array(&m_style, value);
    return *this;
}

Style& set_image_colorkey(const lv_image_colorkey_t * value) noexcept {
    lv_style_set_image_colorkey(&m_style, value);
    return *this;
}

Style& set_length(int32_t value) noexcept {
    lv_style_set_length(&m_style, value);
    return *this;
}

Style& set_line_dash_gap(int32_t value) noexcept {
    lv_style_set_line_dash_gap(&m_style, value);
    return *this;
}

Style& set_line_dash_width(int32_t value) noexcept {
    lv_style_set_line_dash_width(&m_style, value);
    return *this;
}

Style& set_opa_layered(lv_opa_t value) noexcept {
    lv_style_set_opa_layered(&m_style, value);
    return *this;
}

Style& set_pad_radial(int32_t value) noexcept {
    lv_style_set_pad_radial(&m_style, value);
    return *this;
}

Style& set_radial_offset(int32_t value) noexcept {
    lv_style_set_radial_offset(&m_style, value);
    return *this;
}

Style& set_recolor(lv_color_t value) noexcept {
    lv_style_set_recolor(&m_style, value);
    return *this;
}

Style& set_recolor_opa(lv_opa_t value) noexcept {
    lv_style_set_recolor_opa(&m_style, value);
    return *this;
}

Style& set_rotary_sensitivity(uint32_t value) noexcept {
    lv_style_set_rotary_sensitivity(&m_style, value);
    return *this;
}

Style& set_text_outline_stroke_color(lv_color_t value) noexcept {
    lv_style_set_text_outline_stroke_color(&m_style, value);
    return *this;
}

Style& set_text_outline_stroke_opa(lv_opa_t value) noexcept {
    lv_style_set_text_outline_stroke_opa(&m_style, value);
    return *this;
}

Style& set_text_outline_stroke_width(int32_t value) noexcept {
    lv_style_set_text_outline_stroke_width(&m_style, value);
    return *this;
}

Style& set_transform_skew_x(int32_t value) noexcept {
    lv_style_set_transform_skew_x(&m_style, value);
    return *this;
}

Style& set_transform_skew_y(int32_t value) noexcept {
    lv_style_set_transform_skew_y(&m_style, value);
    return *this;
}

Style& set_translate_radial(int32_t value) noexcept {
    lv_style_set_translate_radial(&m_style, value);
    return *this;
}

Style& set_x(int32_t value) noexcept {
    lv_style_set_x(&m_style, value);
    return *this;
}

Style& set_y(int32_t value) noexcept {
    lv_style_set_y(&m_style, value);
    return *this;
}

